# Generated by Django 4.0.6 on 2022-08-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
    ]
