# Generated by Django 4.0.6 on 2022-08-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_favoritelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
